// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// import "dotenv/config";
import { defineConfig } from "prisma/config";

const environment = process.env.NODE_ENV || 'test';
const envFile = environment === 'production' ? '.env' : `.env.${environment}`;

import dotenv from  "dotenv"
dotenv.config({ path: envFile });

const connectionString = process.env["DATABASE_URL"] as string;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: 'tsx prisma/seed.ts'
  },
  datasource: {
    url: connectionString,
  },
});
